using System;
using System.Collections.Generic;
using System.IO;
using System.Xml;
using System.Linq;
using Newtonsoft.Json; // instalowanie Newtonsoft.Json w pakiecie Nuget

namespace Ćwiczenia2
{
    /// <summary>
    /// Klasa grupa
    /// zawierająca listę studentów
    /// </summary>
    class Grupa : IWritable
    {
        // List studentów
        private List<Student> students;

        // Nazwa grupy
        private string groupName;

        /// <summary>
        /// Główny, jedyny dostępny konstruktor
        /// </summary>
        /// <param name="groupName">Nazwa grupy</param>
        public Grupa(string groupName)
        {
            this.groupName = groupName;
            this.students = new List<Student>();
        }

        /// <summary>
        /// Metoda dodająca studenta do grupy
        /// </summary>
        /// <param name="student">Student do dodania</param>
        public void AddStudent(Student student)
        {
            this.students.Add(student);
        }

        /// <summary>
        /// Metoda agregująca dwie listy studentów
        /// </summary>
        /// <param name="students">Lista studentów do dodania</param>
        public void AddStudents(List<Student> students)
        {
            this.students.AddRange(students);
        }

        /// <summary>
        /// Lista arbitralnej długości studentów do agregacji
        /// </summary>
        /// <param name="students">Lista studentów do dodania</param>
        public void AddStudents(params Student[] students)
        {
            this.students.AddRange(students);
        }

        /// <summary>
        /// Usunięcie studenta przez index w liście
        /// </summary>
        /// <param name="index">Indeks z którego student jest usuwany</param>
        public void DeleteStudent(int index)
        {
            this.students.RemoveAt(index);
        }

        /// <summary>
        /// Usunięcie studenta przez porównanie każdego indexu studenta z indexem studenta
        /// podanego przez parametr
        /// </summary>
        /// <param name="student">Student do usunięcie</param>
        public void DeleteStudent(Student student)
        {
            this.students.Remove(students.Single(s => s.Index == student.Index));
        }

        /// <summary>
        /// Zapisywanie do pliku w formacie xml.
        /// </summary>
        /// <param name="outputFileName">Nazwa pliku, w którym będą zapisane dane</param>
        public void WriteToXmlFile(string outputFileName)
        {
            outputFileName += ".xml";
            XmlWriterSettings settings = new XmlWriterSettings();
            settings.Indent = true;
            XmlWriter writer = XmlWriter.Create(@outputFileName, settings);
            writer.WriteStartDocument();
            writer.WriteStartElement("grupa");
            writer.WriteAttributeString("createdAt", DateTime.Now.ToString("MM/dd/yyyy").Replace("/", "."));
            writer.WriteAttributeString("author", System.Security.Principal.WindowsIdentity.GetCurrent().Name);
            writer.WriteComment("This file is generated by the program");
            writer.WriteStartElement("studenci");
            foreach(Student student in students)
            {
                WriteToXmlFile(writer, student);
            }
            writer.WriteEndElement();
            writer.WriteEndElement();
            writer.WriteEndDocument();
            writer.Flush();
            writer.Close();
        }

        /// <summary>
        /// Prywatna metoda do formatowania zapisywanego studenta
        /// </summary>
        /// <param name="writer">Xml writer wykorzystywany przy formatowanym zapise do pliku</param>
        /// <param name="student">Student do zapisu</param>
        private void WriteToXmlFile(XmlWriter writer, Student student)
        {
            writer.WriteStartElement("student");
            writer.WriteAttributeString("indexNumber", student.Index);
            writer.WriteElementString("fname", student.Name);
            writer.WriteElementString("lname", student.LName);
            writer.WriteElementString("birthdate", student.DateOfBirth);
            writer.WriteElementString("email", student.Email);
            writer.WriteElementString("mothersName", student.MName);
            writer.WriteElementString("fathersName", student.FName);
            writer.WriteStartElement("studies");
            writer.WriteElementString("name", student.Type);
            writer.WriteElementString("mode", student.Type1);
            writer.WriteEndElement();
            writer.WriteEndElement();
        }

        /// <summary>
        /// Zapisywanie do pliku w formacie json.
        /// </summary>
        /// <param name="outputFileName"></param>
        public void WriteToJsonFile(string outputFileName)
        {
            outputFileName += ".json";
            StreamWriter streamWriter = new StreamWriter(@outputFileName);
            JsonWriter writer = new JsonTextWriter(streamWriter);
            writer.Formatting = Newtonsoft.Json.Formatting.Indented;
            writer.WriteStartObject();
            writer.WritePropertyName("grupa: " + groupName);
            writer.WriteStartObject();
            writer.WritePropertyName("createdAt");
            writer.WriteValue(DateTime.Now.ToString("MM/dd/yyyy").Replace("/", "."));
            writer.WritePropertyName("author");
            writer.WriteValue(System.Security.Principal.WindowsIdentity.GetCurrent().Name);
            writer.WritePropertyName("studenci");
            writer.WriteStartArray();
            foreach(Student student in students)
            {
                WriteToJsonFile(writer, student);
            }
            writer.WriteEnd();
            writer.WriteEndObject();
            writer.Close();
        }

        /// <summary>
        /// Prywatna metoda do formatowania zapisywanego studenta
        /// </summary>
        /// <param name="writer">Json writer wykorzystywany przy formatowanym zapise do pliku</param>
        /// <param name="student">Student do zapisu</param>
        private void WriteToJsonFile(JsonWriter writer, Student student)
        {
            writer.WriteStartObject();
            writer.WritePropertyName("index");
            writer.WriteValue(student.Index);
            writer.WritePropertyName("fname");
            writer.WriteValue(student.Name);
            writer.WritePropertyName("lname");
            writer.WriteValue(student.LName);
            writer.WritePropertyName("birthdate");
            writer.WriteValue(student.DateOfBirth);
            writer.WritePropertyName("email");
            writer.WriteValue(student.Email);
            writer.WritePropertyName("mothersName");
            writer.WriteValue(student.MName);
            writer.WritePropertyName("fathersName");
            writer.WriteValue(student.FName);
            writer.WritePropertyName("studies");
            writer.WriteStartObject();
            writer.WritePropertyName("name");
            writer.WriteValue(student.Type);
            writer.WritePropertyName("mode");
            writer.WriteValue(student.Type1);
            writer.WriteEndObject();
            writer.WriteEndObject();
        }
    }
}
